defaults:
  - model: moe
  - training: default
  - mlflow: default
  - _self_

seed: 42

paths:
  dati: /ipazianas/pasquini/output_graph_analysis/feb-oct_hour_2022/60d486e0adcc11f1a4ef08f1eaf4fe18/features_extraction/edge_index/dati_orari.pt
  output_root: /ipazianas/pasquini/bernardi/MOE/result
  checkpoint_dir: /ipazianas/pasquini/bernardi/MOE/checkpoint
  hydra_giorno: ${paths.output_root}/hydra/${now:%Y-%m-%d}
  run_dir: ${paths.hydra_giorno}/${indice_run:${paths.hydra_giorno}}

  log_file: ${paths.run_dir}/run.log
  assegnazioni: ${paths.run_dir}/test_per_grafo.csv
  storico: ${paths.run_dir}/storico.csv
  leiden: ${paths.run_dir}/leiden_per_grafo.csv
  louvain: ${paths.run_dir}/louvain_per_grafo.csv

hydra:
  run:
    dir: ${paths.run_dir}
  sweep:
    dir: ${paths.hydra_giorno}/multirun/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false    
