num_epochs: 300
lr: 0.005
weight_decay: 0.0005


grafi_per_step: 16


split: [0.7, 0.15, 0.15]

beta: 0.5
gamma: 1.0
tau: 1.0

grad_clip: 1.0
patience: 40


lr_factor: 0.5
lr_patience: 10

checkpoint_monitor: Q_val
checkpoint_mode: max
log_every: 1
